name: Node.js CI

env:
  DIST_PATH: 'dist'
  ARTIFACT_NAME: 'ezeep Blue office-add-in'
  MODULE_VERSION: '1.0.${{ github.run_number }}'   # update MAJOR and MINOR version here

on:
  push:
    branches: [ "main","feature/publish" ]
  workflow-dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }} to build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: '${{ env.DIST_PATH }}'

  cdn-upload:
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:
 
    - name: Download npm artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: "artifacts/v${{ env.MODULE_VERSION }}"
    
    - name: list directory
      run: |
        ls -lR

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload artifact to blob storage
      run: |
          azenv='${{ secrets.AZURE_ENVIRONMENT }}'
          account=$(jq -crM .storage.account <<< $azenv)
          container=$(jq -crM .storage.container <<< $azenv)

          az storage blob upload-batch \
            --auth-mode login \
            --account-name $account \
            -d $container \
            -s "artifacts" \
            -o none

    - name: Azure CLI logout
      run: |
        az logout
        az cache purge
        az account clear
      if: always()
