name: Node.js CI

env:
  DIST_PATH: 'dist'
  ARTIFACT_NAME: 'ezeep-msoffice-addin'
  MODULE_VERSION: '1.0.${{ github.run_number }}'   # update MAJOR and MINOR version here
  PRERELEASE: false

on:
  push:
    branches: [ "main","feature/publish" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }} to build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: '${{ env.DIST_PATH }}'

    - name: Zip npm artifact for release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: ${{ env.DIST_PATH }}
        path: '.'
        filename: ${{ env.ARTIFACT_NAME }}

    - name: Create release with npm package
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ env.MODULE_VERSION }}"
        prerelease: ${{ env.PRERELEASE }}
        artifacts: "${{ env.DIST_PATH }}/${{ env.ARTIFACT_NAME }}"
        token: ${{ secrets.GITHUB_TOKEN }}

  cdn-upload:
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download npm artifact
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: "artifacts/v${{ env.MODULE_VERSION }}"

    - name: list directory
      run: |
        ls -lR

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload artifact to blob storage
      run: |
          azenv='${{ secrets.AZURE_ENVIRONMENT }}'
          account=$(jq -crM .storage.account <<< $azenv)
          container=$(jq -crM .storage.container <<< $azenv)

          az storage blob upload-batch \
            --auth-mode login \
            --account-name $account \
            -d $container \
            -s "artifacts" \
            -o none

    - name: Purge CDN endpoint
      run: |
           azenv='${{ secrets.AZURE_ENVIRONMENT }}'
           resourceGroup=$(jq -crM .resourceGroup <<< $azenv)
           profile=$(jq -crM .cdn.profileName <<< $azenv)
           endpoint=$(jq -crM .cdn.endpoint.name <<< $azenv)
           container=$(jq -crM .storage.container <<< $azenv)

           az cdn endpoint purge \
             -g $resourceGroup \
             --profile-name $profile \
             -n $endpoint \
             --content-paths "/$container/*" \
             --no-wait \
             -o none

    - name: Azure CLI logout
      run: |
        az logout
        az cache purge
        az account clear
      if: always()
